Traceback (most recent call last):
  File "/home/kk/trust/trust_auto_labeling_partition_cifar10.py", line 221, in <module>
    parser.add_argument('--per_cls_cnt', type='int', 
  File "/home/kk/anaconda3/envs/pytorch/lib/python3.9/argparse.py", line 1421, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'int' is not callable
